---
title: "Hazard Ratings Graph"
author: "Nina Di Cara"
date: "30/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(dplyr)
library(tidyr)
library(ggplot2)

data <- read.table(here("data", "21-sept-survey.txt"), sep = "\t", header = TRUE, encoding="utf-8")

# Add a person ID colum
data$ID <- seq.int(nrow(data))

# Do some initial tidying
data <- data %>% 
  mutate(project = as.factor(project))

hazards <- c(
  "Data Science (general)",
  "Automates decision making",
  "Classifies or ranks people",
  "Difficult to understand",
  "Lacks community involvement",
  "Lacks informed consent",
  "Danger of misuse",
  "May cause direct harm",
  "High environmental cost",
  "Risk to privacy",
  "Reinforces existing biases"
)

```


```{r scores}

data %>%
  select(contains("eval")) %>%
  mutate(across(everything(), as.factor)) %>%
  pivot_longer(cols = everything(), names_to = "Question", values_to = "Score", names_prefix = "eval.") %>%
  drop_na() %>%
  count(Question, Score) %>%
  write.csv(., here("data", "ratings.csv"))

```


```{r get-rankings}

# Overwrite data with a longer version of the hazard ratings data, so the timepoint of the ratings is a column
data <- data %>% 
  select(ID, role, project, hazards.1, hazards.2) %>%
  pivot_longer(cols = c("hazards.1", "hazards.2"), names_pattern = "hazards.(.)", values_to = "hazards") %>%
  rename(timepoint = name)

ratings <- data %>% pull("hazards") %>% strsplit(., ",")

# Initialise objects 
i = 1
ratings_clean <-vector("list",42)

# This loop will go through each set of responses and indicate if each hazard is present or not. 
for (response in ratings) {
  
    # Set up a list for the next person's responses
    next_response <- c(i)
    
    # Make a vector of TRUE/FALSE if each hazard is in the list
    for (hazard in hazards) {
      val <- hazard %in% response
      next_response <- c(next_response, val)
    }
    
    # Add the next response to the list of clean ratings
    ratings_clean[[i]] <- next_response
    
    # Increase i for the next iteration
    i = i + 1
}

ratings_clean <- as.data.frame(do.call(rbind, ratings_clean))
colnames(ratings_clean) <- c("ID", hazards)
ratings_clean <- ratings_clean %>% select(!ID)

# Add the ratings back to the main dataset 
data <- cbind(data, ratings_clean)

# Remove data no longer needed
rm(ratings, ratings_clean)

```

```{r graph}

data %>% 
  mutate(ID = as.factor(ID), # Change this so it doesn't get caught in 'numeric' net
         timepoint = as.factor(timepoint),
         timepoint = recode_factor(timepoint, 
                                   "1" = "Before", "2" = "After")) %>% 
  group_by(project, timepoint) %>%
  summarise(across(where(is.numeric), sum)) %>%
  ungroup() %>%
  pivot_longer(cols = hazards, names_to = "hazard", values_to = "ratings") %>%
  ggplot(aes(x=ratings, y=hazard)) +
  geom_line(aes(group = hazard)) +
  geom_point(aes(color = timepoint), size = 3) + 
  facet_wrap(~project) +
  theme_bw() + 
  xlab("\nNumber of times selected") + 
  ylab("Hazard Label\n") + 
  guides(color=guide_legend(title="Timepoint"))

ggsave("rating-changes.png", width = 6, height = 4, units = "in", dpi=330)

```


```{r graph2}

data %>% 
  mutate(ID = as.factor(ID), # Change this so it doesn't get caught in 'numeric' net
         timepoint = as.factor(timepoint),
         timepoint = recode_factor(timepoint, 
                                   "1" = "Before", "2" = "After")) %>% 
  select(!hazards) %>%
  pivot_longer(cols = hazards, names_to = "hazard", values_to = "ratings") %>%
  pivot_wider(names_from = "timepoint", values_from = "ratings") %>%
  mutate(diff = After - Before) %>%
  count(hazard, diff) %>%
  ungroup() %>%
  mutate(value = diff * n) %>%
  #pivot_wider(names_from = diff, values_from = n, values_fill = 0) %>%
  #rename("Up" = "1", "Down" = "-1") %>%
  # Make into a pyramid plot
  ggplot(aes(y = hazard, x = value)) +
  geom_point(aes(color = as.factor(diff)), size = 3) + 
  #geom_line(arrow = arrow(ends="first", type = "closed")) +
  #geom_line(arrow = arrow(ends="last", type = "closed")) +
  geom_arrow(start = 0) +
  theme_minimal() +
  theme(panel.grid.minor = element_blank()) +
  #coord_flip() +
  ylab("Hazard Label\n") + 
  xlab("\nNumber of people who added or removed labels")

  # geom_bar(aes(y = -Down), stat = "identity", fill = "#fc8d62") + 
  # geom_bar(aes(y = Up), stat = "identity", fill = "#66c2a5") + 


# ggsave("ratings-moved.png", width = 6, height = 4, units = "in", dpi=330)
```